/*
===============================================================================

This source file is part of CGRE
    (C Graphics Rendering Engine)
CGRE is made available under the MIT License.

Copyright (c) 2016-2017 Javier Castillo II

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===============================================================================
*/

#include <cgre/core/common.h>

#include <string.h>

/**
 * @file include/cgre/core/common.h
 * @brief Core common header file
 *
 * This contains the macros, definitions, structs and public API function
 * declarations for core operations
 */

/**
 * @def CGRE_NODE_BITMASK
 * Node bitfield mask
 */

/**
 * @def CGRE_NODE_BITFIELD_CMP
 * Node bitfield compare
 *
 * @code
 * if (CGRE_NODE_BITFIELD_CMP(node->state,
 *         CGRE_NODE_INITIALIZED & CGRE_NODE_NOVALUE)) {
 *     // ... do something
 * }
 * @endcode
 */

/**
 * @def CGRE_NODE_INITIALIZED
 * Initialized node bitfield
 */

/**
 * @def CGRE_NODE_VALUE
 * Node value bitfield
 */

/**
 * @struct cgre_node include/cgre/core/common.h <cgre/core/common.h>
 * @brief Node struct
 *
 * @remark
 * Operations on individual `cgre_node`s are not thread-safe. A node can only
 * belong to and be manipulated by a single `cgre_node_tree` or
 * `cgre_node_list` which operate thread-safely however.
 *
 * @warning
 * To ensure thread-safety with collections, do not ever modify a `cgre_node`
 * value directly. Initialize a new node with the new value, copy the key and
 * use the collection replace method instead.
 *
 * This struct provides the interface for collections. The operations on values
 * are independent of the collections, so node operations will not impact a
 * particular node value across any threads.
 *
 * @var void* value
 * The pointer to the value of the node.
 * @var struct cgre_node* link[2]
 * The left/right pointers to children nodes
 * @var cgre_uint_t key
 * A unique key typically generated by the `CGRE_HASH` macro.
 * @var cgre_uint_t state
 * The state values can be used as bit fields by the collections functions or
 * associated valye type operations.
 */

/**
 * @brief Generate a hash from a key
 *
 * @param[in] key Value to be hashed
 * @return cgre_uint_t hash
 */
cgre_uint_t cgre_hash(void* key)
{
    const char* s = (const char*) key;
    cgre_uint_t sum = 0;
    cgre_int_t interval = 0;
    for (cgre_int_t idx = 0; s[idx] != 0; idx++) {
        if (interval == 1) {
            sum <<= sizeof(char);
            interval--;
        }
        sum ^= (cgre_int_t) s[idx];
        interval++;
    }
    return sum;
}

/**
 * @brief Initialize a node with empty values
 *
 * @param[in] node Node to initialize
 * @param[in] key Key to set for Node
 * @param[in] value Node value pointer
 * @return cgre_node pointer or NULL if error
 */
struct cgre_node* cgre_node_initialize(
        struct cgre_node* node,
        cgre_uint_t key,
        void* value)
{
    node->key = key;
    node->value = value;
    node->link[0] = NULL;
    node->link[1] = NULL;
    return node;
}

/**
 * @brief Uninitialize a node
 *
 * @param[in] node Node to uninitialize
 * @return void pointer to value
 */
void* cgre_node_uninitialize(
        struct cgre_node* node)
{
    void *result = node->value;
    node->value = NULL;
    node->link[0] = NULL;
    node->link[1] = NULL;
    node->key = 0;
    return result;
}
